version: "3.8"
services:
    client:
        volumes: 
            - /app/node_modules
            - ./client/:/app/
        build: 
            context: ./client
        ports:
            - "3000:3000"
    server:
        volumes:
            - /app/node_modules
            - ./server/:/app
        build: 
            context: ./server
        ports:
            - "8000:8000"
        depends_on:
            - mysql_db
    mysql_db:
        image: mysql
        environment:
            MYSQL_DATABASE: mohaji
            MYSQL_USER: user
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
        networks:
            - net
    networks:
        net:
            driver: bridge
